# Generated by Django 5.0.7 on 2024-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groceryapp', '0002_rename_stock_price_stock_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
